# Generated by Django 5.1.1 on 2024-09-27 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("album", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Musician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=512)),
                ("last_name", models.CharField(max_length=512)),
                ("email", models.EmailField(max_length=512)),
                ("phone_number", models.CharField(max_length=512)),
                ("instrument_type", models.CharField(max_length=512)),
                (
                    "album",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="album.album",
                    ),
                ),
            ],
        ),
    ]
